/* The following code was generated by JFlex 1.4.3 on 4/18/12 3:36 PM */

/*
 *  Beinagrind fyrir lesgreini.
 *
 *  Höfundur: Snorri Agnarsson
 * 			  Ívar Haukur Sævarsson
 *
 *  Athugið að hér er verið að nota Java en ekki C eða C++.
 *  Þessa skrá má þýða og keyra með eftirfarandi skipunum:
 *     java -jar JFlex.jar morpho.jflex
 *     javac MyLexer.java
 *     java MyLexer < inntak
 */


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 4/18/12 3:36 PM from the specification file
 * <tt>Hercules.jflex</tt>
 */
public class HerculesLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\1\0\1\45\1\24\1\42\1\46\1\23\22\0\1\45\1\27"+
    "\1\11\2\6\1\5\1\26\1\20\2\6\1\5\1\4\1\6\1\4"+
    "\1\2\1\5\4\21\4\22\2\1\1\5\1\41\1\5\1\7\2\5"+
    "\1\0\4\10\1\3\25\10\1\6\1\12\1\6\1\5\1\10\1\0"+
    "\1\33\1\13\2\10\1\32\1\16\1\10\1\37\1\35\2\10\1\31"+
    "\1\10\1\15\3\10\1\17\1\34\1\14\1\30\1\40\1\36\3\10"+
    "\1\43\1\25\1\44\1\5\6\0\1\42\44\0\1\10\12\0\1\10"+
    "\4\0\1\10\5\0\27\10\1\0\37\10\1\0\u013f\10\31\0\162\10"+
    "\4\0\14\10\16\0\5\10\11\0\1\10\213\0\1\10\13\0\1\10"+
    "\1\0\3\10\1\0\1\10\1\0\24\10\1\0\54\10\1\0\46\10"+
    "\1\0\5\10\4\0\202\10\10\0\105\10\1\0\46\10\2\0\2\10"+
    "\6\0\20\10\41\0\46\10\2\0\1\10\7\0\47\10\110\0\33\10"+
    "\5\0\3\10\56\0\32\10\5\0\13\10\43\0\2\10\1\0\143\10"+
    "\1\0\1\10\17\0\2\10\7\0\2\10\12\0\3\10\2\0\1\10"+
    "\20\0\1\10\1\0\36\10\35\0\3\10\60\0\46\10\13\0\1\10"+
    "\u0152\0\66\10\3\0\1\10\22\0\1\10\7\0\12\10\43\0\10\10"+
    "\2\0\2\10\2\0\26\10\1\0\7\10\1\0\1\10\3\0\4\10"+
    "\3\0\1\10\36\0\2\10\1\0\3\10\16\0\2\10\23\0\6\10"+
    "\4\0\2\10\2\0\26\10\1\0\7\10\1\0\2\10\1\0\2\10"+
    "\1\0\2\10\37\0\4\10\1\0\1\10\23\0\3\10\20\0\11\10"+
    "\1\0\3\10\1\0\26\10\1\0\7\10\1\0\2\10\1\0\5\10"+
    "\3\0\1\10\22\0\1\10\17\0\2\10\43\0\10\10\2\0\2\10"+
    "\2\0\26\10\1\0\7\10\1\0\2\10\1\0\5\10\3\0\1\10"+
    "\36\0\2\10\1\0\3\10\17\0\1\10\21\0\1\10\1\0\6\10"+
    "\3\0\3\10\1\0\4\10\3\0\2\10\1\0\1\10\1\0\2\10"+
    "\3\0\2\10\3\0\3\10\3\0\10\10\1\0\3\10\113\0\10\10"+
    "\1\0\3\10\1\0\27\10\1\0\12\10\1\0\5\10\46\0\2\10"+
    "\43\0\10\10\1\0\3\10\1\0\27\10\1\0\12\10\1\0\5\10"+
    "\3\0\1\10\40\0\1\10\1\0\2\10\43\0\10\10\1\0\3\10"+
    "\1\0\27\10\1\0\20\10\46\0\2\10\43\0\22\10\3\0\30\10"+
    "\1\0\11\10\1\0\1\10\2\0\7\10\72\0\60\10\1\0\2\10"+
    "\14\0\7\10\72\0\2\10\1\0\1\10\2\0\2\10\1\0\1\10"+
    "\2\0\1\10\6\0\4\10\1\0\7\10\1\0\3\10\1\0\1\10"+
    "\1\0\1\10\2\0\2\10\1\0\4\10\1\0\2\10\11\0\1\10"+
    "\2\0\5\10\1\0\1\10\25\0\2\10\42\0\1\10\77\0\10\10"+
    "\1\0\42\10\35\0\4\10\164\0\42\10\1\0\5\10\1\0\2\10"+
    "\45\0\6\10\112\0\46\10\12\0\51\10\7\0\132\10\5\0\104\10"+
    "\5\0\122\10\6\0\7\10\1\0\77\10\1\0\1\10\1\0\4\10"+
    "\2\0\7\10\1\0\1\10\1\0\4\10\2\0\47\10\1\0\1\10"+
    "\1\0\4\10\2\0\37\10\1\0\1\10\1\0\4\10\2\0\7\10"+
    "\1\0\1\10\1\0\4\10\2\0\7\10\1\0\7\10\1\0\27\10"+
    "\1\0\37\10\1\0\1\10\1\0\4\10\2\0\7\10\1\0\47\10"+
    "\1\0\23\10\105\0\125\10\14\0\u026c\10\2\0\10\10\12\0\32\10"+
    "\5\0\113\10\25\0\15\10\1\0\4\10\16\0\22\10\16\0\22\10"+
    "\16\0\15\10\1\0\3\10\17\0\64\10\43\0\1\10\4\0\1\10"+
    "\103\0\130\10\10\0\51\10\127\0\35\10\63\0\36\10\2\0\5\10"+
    "\u038b\0\154\10\224\0\234\10\4\0\132\10\6\0\26\10\2\0\6\10"+
    "\2\0\46\10\2\0\6\10\2\0\10\10\1\0\1\10\1\0\1\10"+
    "\1\0\1\10\1\0\37\10\2\0\65\10\1\0\7\10\1\0\1\10"+
    "\3\0\3\10\1\0\7\10\3\0\4\10\2\0\6\10\4\0\15\10"+
    "\5\0\3\10\1\0\7\10\53\0\2\42\107\0\1\10\15\0\1\10"+
    "\202\0\1\10\4\0\1\10\2\0\12\10\1\0\1\10\3\0\5\10"+
    "\6\0\1\10\1\0\1\10\1\0\1\10\1\0\4\10\1\0\3\10"+
    "\1\0\7\10\3\0\3\10\5\0\5\10\u0ebb\0\2\10\52\0\5\10"+
    "\5\0\2\10\4\0\126\10\6\0\3\10\1\0\132\10\1\0\4\10"+
    "\5\0\50\10\4\0\136\10\21\0\30\10\70\0\20\10\u0200\0\u19b6\10"+
    "\112\0\u51a6\10\132\0\u048d\10\u0773\0\u2ba4\10\u215c\0\u012e\10\2\0\73\10"+
    "\225\0\7\10\14\0\5\10\5\0\1\10\1\0\12\10\1\0\15\10"+
    "\1\0\5\10\1\0\1\10\1\0\2\10\1\0\2\10\1\0\154\10"+
    "\41\0\u016b\10\22\0\100\10\2\0\66\10\50\0\14\10\164\0\5\10"+
    "\1\0\207\10\44\0\32\10\6\0\32\10\13\0\131\10\3\0\6\10"+
    "\2\0\6\10\2\0\6\10\2\0\3\10\43\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\3\1\1"+
    "\4\4\1\1\1\6\2\5\1\7\4\4\2\3\3\10"+
    "\2\0\1\2\1\0\5\4\2\0\1\11\1\12\1\4"+
    "\1\13\2\4\4\0\1\14\2\4\1\15\2\4\2\0"+
    "\2\4\1\16\5\0\1\17\1\4\1\20\1\4\3\21"+
    "\1\22\1\23\1\24\1\14\1\0\2\4\1\25\1\26"+
    "\1\27\1\30";

  private static int [] zzUnpackAction() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\116\0\234\0\303\0\303"+
    "\0\352\0\u0111\0\u0138\0\u015f\0\u0186\0\u01ad\0\116\0\u01d4"+
    "\0\u01fb\0\303\0\u0222\0\u0249\0\u0270\0\u0297\0\u02be\0\u02e5"+
    "\0\116\0\u030c\0\u0333\0\u035a\0\352\0\116\0\u0381\0\u03a8"+
    "\0\u03cf\0\u03f6\0\u041d\0\u0444\0\u046b\0\u0492\0\303\0\303"+
    "\0\u04b9\0\234\0\u04e0\0\u0507\0\u052e\0\u0555\0\u057c\0\u05a3"+
    "\0\u05ca\0\u05f1\0\u0618\0\234\0\u063f\0\u0666\0\u068d\0\u06b4"+
    "\0\u06db\0\u0702\0\234\0\u0729\0\u0750\0\u0777\0\u079e\0\u07c5"+
    "\0\234\0\u07ec\0\u0813\0\u083a\0\u0861\0\116\0\u0729\0\116"+
    "\0\116\0\116\0\u0888\0\u0888\0\u08af\0\u08d6\0\234\0\116"+
    "\0\234\0\234";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\2\7\1\5\1\10\1\6"+
    "\1\11\1\3\1\6\1\12\1\13\1\14\1\15\1\16"+
    "\2\4\2\17\1\20\1\21\1\22\2\6\1\23\2\6"+
    "\1\24\1\25\1\6\1\26\1\27\1\3\1\30\1\5"+
    "\2\17\41\31\1\32\1\31\1\33\3\31\50\0\1\4"+
    "\1\34\16\0\2\4\25\0\1\6\1\0\1\6\4\0"+
    "\1\6\2\0\5\6\1\0\2\6\5\0\11\6\12\0"+
    "\2\7\1\0\1\7\15\0\3\7\17\0\11\35\1\36"+
    "\1\37\34\35\1\0\1\6\1\0\1\6\4\0\1\6"+
    "\2\0\4\6\1\40\1\0\2\6\5\0\11\6\7\0"+
    "\1\6\1\0\1\6\4\0\1\6\2\0\5\6\1\0"+
    "\2\6\5\0\1\41\10\6\7\0\1\6\1\0\1\6"+
    "\4\0\1\6\2\0\5\6\1\0\2\6\5\0\1\42"+
    "\2\6\1\43\5\6\7\0\1\6\1\0\1\6\4\0"+
    "\1\6\2\0\5\6\1\0\2\6\5\0\2\6\1\44"+
    "\6\6\6\0\12\45\1\46\5\45\1\0\26\45\4\0"+
    "\2\7\1\0\1\7\15\0\1\47\2\7\23\0\2\7"+
    "\1\0\1\7\15\0\1\7\1\50\1\7\20\0\1\6"+
    "\1\0\1\6\4\0\1\6\2\0\5\6\1\0\2\6"+
    "\5\0\1\6\1\51\7\6\7\0\1\6\1\0\1\6"+
    "\4\0\1\6\2\0\3\6\1\52\1\6\1\0\2\6"+
    "\5\0\11\6\7\0\1\6\1\0\1\6\4\0\1\6"+
    "\2\0\5\6\1\0\2\6\5\0\7\6\1\53\1\6"+
    "\7\0\1\6\1\0\1\6\4\0\1\6\2\0\5\6"+
    "\1\0\2\6\5\0\3\6\1\54\5\6\47\0\1\55"+
    "\46\0\1\56\46\0\1\57\46\0\1\60\6\0\1\61"+
    "\17\0\2\61\35\0\12\35\25\0\1\6\1\0\1\6"+
    "\4\0\1\6\2\0\5\6\1\0\2\6\5\0\1\62"+
    "\10\6\7\0\1\6\1\0\1\6\4\0\1\6\2\0"+
    "\5\6\1\0\2\6\5\0\1\6\1\63\7\6\7\0"+
    "\1\6\1\0\1\6\4\0\1\6\2\0\2\6\1\64"+
    "\2\6\1\0\2\6\5\0\11\6\7\0\1\6\1\0"+
    "\1\6\4\0\1\6\2\0\5\6\1\0\2\6\5\0"+
    "\1\6\1\65\7\6\7\0\1\6\1\0\1\6\4\0"+
    "\1\6\2\0\1\6\1\66\3\6\1\0\2\6\5\0"+
    "\11\6\26\0\1\36\37\0\10\45\1\67\1\70\25\0"+
    "\1\6\1\0\1\6\4\0\1\6\2\0\5\6\1\0"+
    "\2\6\5\0\4\6\1\71\4\6\7\0\1\6\1\0"+
    "\1\6\4\0\1\6\2\0\5\6\1\0\2\6\5\0"+
    "\5\6\1\72\3\6\7\0\1\6\1\0\1\6\4\0"+
    "\1\6\2\0\4\6\1\73\1\0\2\6\5\0\11\6"+
    "\47\0\1\74\46\0\1\75\46\0\1\76\46\0\1\77"+
    "\6\0\1\61\1\0\1\100\15\0\2\61\7\0\1\100"+
    "\15\0\1\6\1\0\1\6\4\0\1\6\2\0\5\6"+
    "\1\0\2\6\5\0\2\6\1\101\6\6\7\0\1\6"+
    "\1\0\1\6\4\0\1\6\2\0\5\6\1\0\2\6"+
    "\5\0\1\6\1\101\7\6\7\0\1\6\1\0\1\6"+
    "\4\0\1\6\2\0\5\6\1\0\2\6\5\0\4\6"+
    "\1\62\4\6\7\0\1\6\1\0\1\6\4\0\1\6"+
    "\2\0\5\6\1\0\2\6\5\0\1\102\10\6\26\0"+
    "\1\36\2\70\44\0\1\36\2\45\25\0\1\6\1\0"+
    "\1\6\4\0\1\6\2\0\5\6\1\0\2\6\5\0"+
    "\2\6\1\103\6\6\7\0\1\6\1\0\1\6\4\0"+
    "\1\6\2\0\5\6\1\0\2\6\5\0\1\6\1\104"+
    "\7\6\6\0\23\74\1\105\1\106\15\74\1\107\3\74"+
    "\1\107\41\0\1\110\51\0\1\111\43\0\1\112\6\0"+
    "\1\113\2\0\1\114\14\0\2\113\25\0\1\6\1\0"+
    "\1\6\4\0\1\6\2\0\4\6\1\115\1\0\2\6"+
    "\5\0\11\6\7\0\1\6\1\0\1\6\4\0\1\6"+
    "\2\0\5\6\1\0\2\6\5\0\5\6\1\116\3\6"+
    "\7\0\1\6\1\0\1\6\4\0\1\6\2\0\5\6"+
    "\1\0\2\6\5\0\2\6\1\117\6\6\6\0\23\74"+
    "\1\105\1\120\15\74\1\107\3\74\1\107\1\0\1\113"+
    "\17\0\2\113\25\0\1\6\1\0\1\6\4\0\1\6"+
    "\2\0\2\6\1\121\2\6\1\0\2\6\5\0\11\6"+
    "\7\0\1\6\1\0\1\6\4\0\1\6\2\0\3\6"+
    "\1\122\1\6\1\0\2\6\5\0\11\6\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2301];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\11\1\1\11\11\1\1\11"+
    "\2\1\2\0\1\11\1\0\5\1\2\0\6\1\4\0"+
    "\6\1\2\0\3\1\5\0\5\1\1\11\1\1\3\11"+
    "\1\1\1\0\3\1\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
int nesting = 0;

public HerculesParser yyHerculesParser;

public HerculesLexer( java.io.Reader r, HerculesParser yyHerculesParser )
{
	this(r);
	this.yyHerculesParser = yyHerculesParser;
}

public int getLine() { return yyline; }
public int getColumn() { return yycolumn; }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public HerculesLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public HerculesLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1234) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 19: 
          { if( --nesting==0 )
	{
		yybegin(YYINITIAL);
	}
          }
        case 25: break;
        case 12: 
          { yyHerculesParser.yylval = new HerculesParserVal(yytext());
	return HerculesParser.DOUBLE;
          }
        case 26: break;
        case 16: 
          { return HerculesParser.ELSE;
          }
        case 27: break;
        case 5: 
          { yyHerculesParser.yylval = new HerculesParserVal(yytext());
	switch( yycharat(0) )
	{
		case '?':
		case '~':
		case '^':
		case ':':
		case '|':
		case '&':
		case '=':
		case '<':
		case '>':
		case '!':
		case '+':
		case '-':
		default:
	}
          }
        case 28: break;
        case 14: 
          { return HerculesParser.VAR;
          }
        case 29: break;
        case 1: 
          { return HerculesParser.YYERRCODE;
          }
        case 30: break;
        case 9: 
          { return HerculesParser.OR;
          }
        case 31: break;
        case 15: 
          { return HerculesParser.LITERAL;
          }
        case 32: break;
        case 7: 
          { return HerculesParser.NOT;
          }
        case 33: break;
        case 3: 
          { yyHerculesParser.yylval = new HerculesParserVal(yytext());
	return yycharat(0);
          }
        case 34: break;
        case 4: 
          { yyHerculesParser.yylval = new HerculesParserVal(yytext());
	return HerculesParser.NAME;
          }
        case 35: break;
        case 10: 
          { return HerculesParser.AND;
          }
        case 36: break;
        case 13: 
          { return HerculesParser.FUN;
          }
        case 37: break;
        case 21: 
          { return HerculesParser.WHILE;
          }
        case 38: break;
        case 2: 
          { yyHerculesParser.yylval = new HerculesParserVal(yytext());
	return HerculesParser.LITERAL;
          }
        case 39: break;
        case 23: 
          { return HerculesParser.RETURN;
          }
        case 40: break;
        case 24: 
          { return HerculesParser.ELSEIF;
          }
        case 41: break;
        case 20: 
          { nesting++;
          }
        case 42: break;
        case 11: 
          { return HerculesParser.IF;
          }
        case 43: break;
        case 8: 
          { /* ignore */
          }
        case 44: break;
        case 22: 
          // lookahead expression with fixed lookahead length
          yypushback(2);
          { 
          }
        case 45: break;
        case 18: 
          { yybegin(COMMENT); nesting++;
          }
        case 46: break;
        case 6: 
          { 
          }
        case 47: break;
        case 17: 
          // lookahead expression with fixed lookahead length
          yypushback(1);
          { 
          }
        case 48: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
